### ISSUE TITLE
Warning: GroundingDINO not available. Text prompts will use fallback method. Error loading AILab_SegmentV2.py: No module named 'groundingdino' [ComfyUI-RMBG] v2.9.0 | 31 nodes Loaded

### ISSUE THREAD

**Issue by chris1024hub** [1038lab/ComfyUI-RMBG#106]
INSTALL GroundingDINO failed

<img width="1920" height="1044" alt="Image" src="https://github.com/user-attachments/assets/739e6336-3119-4817-ba88-6053f863572c" />

<img width="1920" height="1044" alt="Image" src="https://github.com/user-attachments/assets/460310fe-fbfa-4fd2-9765-5443c89b029b" />

**Comment by 1038lab** [comment]
This is a common issue with the `AILab_SAM2Segment` node — it’s usually caused by a corrupted or incomplete model/tokenizer cache.

You can try this quick fix:

1. **Clear your HuggingFace cache**
   Delete this folder:

   ```
   C:\Users\<YourUsername>\.cache\huggingface
   ```

2. **Delete and reinstall ComfyUI-RMBG**
   Go to your `custom_nodes` folder and delete the `ComfyUI-RMBG` folder.

   Then reinstall it:

   ```bash
   git clone https://github.com/1038lab/ComfyUI-RMBG.git
   ```

3. **Install the requirements**
   Make sure to run:

   ```bash
   pip install -r requirements.txt
   ```

That should fix the issue in most cases. If it still doesn't work, let us know!

**Comment by SakuragiA** [comment]
> This is a common issue with the `AILab_SAM2Segment` node — it’s usually caused by a corrupted or incomplete model/tokenizer cache.
> 
> You can try this quick fix:
> 
> 1. **Clear your HuggingFace cache**
>    Delete this folder:
>    ```
>    C:\Users\<YourUsername>\.cache\huggingface
>    ```
> 2. **Delete and reinstall ComfyUI-RMBG**
>    Go to your `custom_nodes` folder and delete the `ComfyUI-RMBG` folder.
>    Then reinstall it:
>    git clone https://github.com/1038lab/ComfyUI-RMBG.git
> 3. **Install the requirements**
>    Make sure to run:
>    pip install -r requirements.txt
> 
> That should fix the issue in most cases. If it still doesn't work, let us know!

I have the same issue, and I've tried your method but is not working. I've noticed that the issue comes from the AILab_SegmentV2.py.  At line 52, there is the code "DINO_MODELS = ..." and below are the huggingface urls. I've tried to change them to my local file path, but it still doesn't work.

**Comment by chris1024hub** [comment]
> This is a common issue with the `AILab_SAM2Segment` node — it’s usually caused by a corrupted or incomplete model/tokenizer cache.
> 
> You can try this quick fix:
> 
> 1. **Clear your HuggingFace cache**
>    Delete this folder:
>    ```
>    C:\Users\<YourUsername>\.cache\huggingface
>    ```
> 2. **Delete and reinstall ComfyUI-RMBG**
>    Go to your `custom_nodes` folder and delete the `ComfyUI-RMBG` folder.
>    Then reinstall it:
>    git clone https://github.com/1038lab/ComfyUI-RMBG.git
> 3. **Install the requirements**
>    Make sure to run:
>    pip install -r requirements.txt
> 
> That should fix the issue in most cases. If it still doesn't work, let us know!

thanks for you reply , but not working by your method, i try 2 times all failed , will install requirements its has this errs /

<img width="737" height="530" alt="Image" src="https://github.com/user-attachments/assets/d26c668f-3964-41db-ba61-fde044922dc8" />

**Comment by steelan9199** [comment]
好的，这是一个常见的问题，尤其是在 Windows 系统上安装某些 Python 库时。

错误信息 `UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4` 指出，在安装 `groundingdino-py` 这个包的过程中，程序试图用 'gbk' 编码去读取一个文件，但这个文件很可能是用 UTF-8 编码保存的，导致了解码失败。

这里是解决这个问题的最常用且有效的方法。

### **主要解决方案：强制 Python 使用 UTF-8 编码**

你可以通过设置一个环境变量，来指示 Python 统一使用 UTF-8 编码，从而避免这个解码错误。

**第一步：设置环境变量**

在你的 PowerShell 终端（就是你刚才输入命令的那个窗口）里，运行以下命令：

```powershell
$env:PYTHONUTF8=1
```

***注意：*** *这个设置只在当前的终端会话中有效。如果你关闭并重新打开 PowerShell 窗口，需要再次运行这个命令。*

**第二步：重新运行安装命令**

在设置完环境变量的**同一个终端窗口**中，重新运行你原来的安装命令：

```powershell
D:\ai\comfyui20250912\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r requirements.txt
```

这样，`groundingdino-py` 应该就能够成功构建和安装了。

---

### **备用解决方案：升级 Pip 和 Setuptools**

有时候，版本过旧的包管理工具也可能导致一些问题。如果上面的主要方案不生效，可以尝试先升级 `pip` 和 `setuptools`。

**第一步：升级 Pip 和 Setuptools**

运行以下命令：

```powershell
# 升级 pip
D:\ai\comfyui20250912\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

# 升级 setuptools
D:\ai\comfyui20250912\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade setuptools
```

**第二步：重试安装**

升级完成后，再次尝试从 `requirements.txt` 文件进行安装（仍然建议你先执行主要解决方案中的第一步，设置 `PYTHONUTF8` 环境变量）。
